### ISSUE TITLE
Brackets around student inputs in matrix form

### ISSUE THREAD

**Issue by michaelbachtold** [surlabs/STACK#12]
When I create a student input, say [[input:ans1]], and in the settings for this input choose Input Type: Matrix, and provide a model answer say  matrix([1],[2],[3]), then the preview will create three input fields, but I haven't been able to put brackets around those fields. The brackets settings of the question do not seem to affect input fields. 

Is there a way to put brackets around such matrix inputs?

**Comment by sangwinc** [comment]
In the Moodle version of STACK we use some HTML table styling to achieve this.  This may be not obvious (sorry) and may have been missed out of the port to ILIAS...

**Comment by jcopado** [comment]
We hope to find an automatic solution for this on the future, please use Mantis for Bug reports on this plugin
thank you
