### ISSUE TITLE
Feature Request: Nutzen der Release-Funktion von Github

### ISSUE THREAD

**Issue by glor** [surlabs/STACK#54]
Ich denke, dass es die Plugin-Installation erheblich vereinfachen würde, wenn die Release-Funktion von github verwendet würde. Dann kann man zu der eigenen Ilias Installation immer schnell die passende Plugin-version herunterladen ohne, dass man die ganze history und die metadaten mit herunterlädt.

Lediglich ein Update wird dadurch geringfügig komplexer.

**Comment by pawohl** [comment]
BTW, did you try GitHub's download feature?
- ILIAS 5.3 -> https://github.com/ilifau/assStackQuestion/archive/master-ilias53.zip
- ILIAS 5.2 -> https://github.com/ilifau/assStackQuestion/archive/master-ilias52.zip

**Comment by jcopado** [comment]
We have started to use this feature today
Thank you for the suggestion
