### ISSUE TITLE
mat_unblocker(M) not working since addrow(...) is shadowed

### ISSUE THREAD

**Issue by rio-** [surlabs/STACK#60]
This has been discussed and fixed for the moodle plugin as can be seen in [their issue #447](https://github.com/maths/moodle-qtype_stack/issues/447).

STACKS `addrow` function overshadows the internal maxima function `addrow`. However, this affects _other functions_ as well: in this case the maxima function `mat_unblocker` that converts block matrices to ordinary matrices internally uses `addrow` and hence fails when STACK is loaded:

`mat_unblocker(diag_matrix(matrix([1,2],[3,4]),matrix([5,6],[7,8])));` produces the error

    Too few arguments supplied to addrow(m,i,j,k); found: [matrix([1,2,0,0],[3,4,0,0]),matrix([0,0,5,6],[0,0,7,8])]

While this is not fixed: any suggestions on how create block diagonal matrices instead of using `diag_matrix` followed by `mat_unblocker`?

**Comment by sangwinc** [comment]
The ILIAS group will need to merge the fix I've already proposed.
See https://github.com/maths/moodle-qtype_stack/issues/447
