### ISSUE TITLE
Frage: Erweiterung des Plugins

### ISSUE THREAD

**Issue by Mastercuber** [surlabs/STACK#64]
Hallo, 

wir arbeite aktuell an der Erweiterung der Validation, dahingehend, dass die Zwischenschritte ebenfalls gespeichert werden können. Für den Zugangspunkt um die aus dem Ilias System empfangenen Daten auszulesen, haben wir uns für die checkUserResponse Funktion der Validation.php entschieden. Um die Anworten mit dem User zu verknüpfen, fehlt uns da eine ID zum Studenten, welher aktuell die Frage beantwortet. Zuerst haben wir die active_id in Betracht genommen, allerdings war diese zu unseren Debugging Sessions Null. Daher wollen wir Sie fragen ob wir bei der active_id richtig lagen, bzw. ob sie uns die Bedeutung hinter der active_id erläutern können. Gibt es noch andere Möglichkeiten an die Studenten ID heranzukommen?

Eine weitere Frage: Sollten wir zur Speicherung der Zwischenschritte eine vorhandene Tabelle nutzen oder lieber eine neue anlegen?

Grüße
Armin Kunkel, Andre Gense

**Comment by fneumann** [comment]
Hallo,

die active_id ist die Kennung eines Nutzers im Test. Sie verbindet in der ILIAS-Tabelle tst_active die usr_id eines Nutzers mit der test_id eines Tests. Bei Nutzung ohne Login kommt noch eine anonymous_id hinzu, da hier der Nutzer immer „anonymous“ ist. In den übrigen Tabellen des Test wird dann nur noch die active_id verwendet.

Zum Speichern der Zwischenschritte wäre auf jeden Fall eine neue Tabelle besser, aber ich muss Sie generell vorwarnen:

In ILIAS wird für Version 6.0 gerade das Testsystem überarbeitet und in sauber getrennte Komponenten (Fragenservice, Fragenpool, Test sowie künftig anderen Verwendungen) aufgeteilt. Dabei wird sich auch die Schnittstelle zu Fragenplugins  grundlegend ändern. Nach dem Refactoring darf eine Testfrage nicht mehr direkt auf Daten ihrer Verwendung zugreifen, sondern das muss über neue Schnittstellen laufen. Eine Verwendung der active_id wie bisher ist dann tabu.
https://docu.ilias.de/goto_docu_wiki_wpage_5280_1357.html

Das Refactoring bedeutet auch für uns als STACK-Maintainer für ILIAS eine große Herausforderung, da viel überarbeitet werden muss. Wir können momentan überhaupt nicht abschätzen, ob die bestehenden Klassen oder Skripte wie validaten.php  in Zukunft noch so bestehen bleiben. Garantieren können wir dazu nichts.

Übrigens haben wir in einem Branch für die Uni Köln eine vereinfachte Form der stufenweisen Rückmeldung implementiert, die aber keine Zwischenschritte speichert, sondern nur die getrennte Evaluation verschiedener Rückmeldebäume erlaubt: 

Für lange Aufgaben soll es zur Verbesserung der Performance und Übersicht möglich sein, während der Bearbeitung Rückmeldungen zu Teilen zu erhalten, selbst wenn noch nicht alle Eingaben ausgefüllt werden. Die Stufenweise Rückmeldung wird mit einer Einstellung in der Frage konfiguriert. Ist sie aktiviert wird an jeder Stelle eines Feedback-Platzhalters im Fragentext ein Rückmeldeknopf angezeigt. Durch Klick auf diesen wird nur der im Platzhalter definierte Rückmeldebaum ausgewertet. Die Auswertung wird analog zur Validierung per Ajax aufgerufen und wenn fertig, unter dem Button eingeblendet. Der Button bleibt aktiv, um ein mehrfaches Aufrufen zu ermöglichen. Voraussetzung ist, dass Feedback-Platzhalter direkt im Fragentext eingefügt sind.

Zu dieser Lösung entspannte sich in den Issues für den Original-Fragentyp für Moodle eine längerer Thread:
https://github.com/maths/moodle-qtype_stack/issues/422

Fazit: Die Funktionalität ist in Diskussion, es wird an mehreren Stellen daran gearbeitet, aber eine gemeinsame Lösung steht noch nicht fest.

Grüße
Fred Neumann
