### ISSUE TITLE
Wrong Versioning for master-ilias6 in plugin.php

### ISSUE THREAD

**Issue by fwolf-ilias** [surlabs/STACK#83]
ILIAS versioning has changed from x.x.x to x.x, therefore the min verison 6.0.0 and max version 6.0.999 should be changed to 6.0 and 6.999. Installation with the newest ILIAS verison 6.3 cant't use this plugin.

**Comment by jcopado** [comment]
Must be solved at this point, please open a bug report on Mantis, which is the official Bug tracker for this plugin
Thank you!
