### ISSUE TITLE
 ErrorException (E_DEPRECATED) in new Ilias Instance

### ISSUE THREAD

**Issue by Xsarior** [surlabs/STACK#93]
I have a new Ilias Intanz up and running with Docker.
Now when I want to add this plugin I get the following error message.

![Error](https://user-images.githubusercontent.com/17991691/143785845-7dee4cc8-3501-4e03-ace6-f18bcd84145a.png)

**Comment by jcopado** [comment]
This issue is currently solved in branch ilias7_stack2021
Please use Mantis bug tracker for bug reports
Thank you
